/* This file is automatically generated based on your hardware design. */
#include "memory_config.h"

struct memory_range_s memory_ranges[] = {
	/* microblaze_0_d_bram_ctrl memory will not be tested since application resides in the same memory */
	{
		"generic_external_memory",
		"axi_emc",
		0x41480000,
		524288,
	},
};

int n_memory_ranges = 1;
